DATATYPE_INTEGER = "Integer"
DATATYPE_FLOAT = "Float"
DATATYPE_BOOLEAN = "Boolean"
DATATYPE_DATE = "Date"
DATATYPE_STRING = "String"

VARTYPE_BINARY = "Binary"
VARTYPE_CATEGORICAL = "Categorical"
VARTYPE_CONTINUOUS = "Continuous"
VARTYPE_UNKNOWN = "Unknown"

ALLOWED_EXTENSIONS = ['csv', 'xls', 'xlsx', 'tsv']